extends Reference

enum HIRC_OBJ_TYPES {
	_00_DUMMY,
	_01_SETTINGS,
	_02_SOUND_SFX,
	_03_EVENT_ACTION,
	_04_EVENT,
	_05_RANDOM_SEQ_CNTR,
	_06_SWITCH_CONTAINER,
	_07_ACTOR_MIXER,
	_08_AUDIO_BUS,
	_09_LAYER_CONTAINER,
	_0A_MUSIC_SEGMENT,
	_0B_MUSIC_TRACK,
	_0C_MUSIC_SWITCH,
	_0D_MUSIC_RANDOM,
	_0E_ATTENUATION,
	_0F_DILOGUE_EVENT,
	_10_MOTION_BUS,
	_11_MOTION_FX,
}
# TODO: There are more, but let's ignore them for now...

enum SOUND_OBJ_ADDITIONAL_PARAMS {
    VOLUME = 0x00,
    LFE = 0x01,
    PITCH = 0x02,
    LPF = 0x03,            # Low-pass filter
    HPF = 0x04,            # High-pass filter
    BUS_VOLUME = 0x05,
    MAKEUP_GAIN = 0x06,
    PRIORITY = 0x07,
    PRIORITY_DISTANCE_OFFSET = 0x08,
    MUTE_RATIO = 0x0B,
    PAN_LR = 0x0C,
    PAN_FR = 0x0D,
    CENTER_PCT = 0x0E,
    DELAY_TIME = 0x0F,
    TRANSITION_TIME = 0x10,
    PROBABILITY = 0x11,
    DIALOGUE_MODE = 0x12,
	#TODO: Add the rest
}

enum CURVE {
	LOG_3,
	SINE,
	LOG_SQRT_2,
	INVSCURVE,
	LINEAR,
	SCURVE,
	EXP_SQRT_2,
	INVSINE,
	EXP_3,
	CONSTANT,
}

enum HIRC_02_INC_OR_STREAMED {EMBEDDED, STREAMED, STREAMED_PREFETCH}
enum HIRC_02_SOUND_OBJ_TYPE {SOUND_SFX, SOUND_VOICE}

enum HIRC_03_EVENT_ACTION_SCOPE {
	GAME_OBJ_SWITCH_OR_TRIGGER = 1,
	GLOBAL = 2,
	GAME_OBJ_REF = 3,
	GAME_OBJ_STATE = 4,
	ALL = 5,
	ALL_EXCEPT_REF = 9,
}
enum HIRC_03_ACTION_TYPE {
	STOP = 1,
	PAUSE = 2,
	RESUME = 3,
	PLAY = 4,
	TRIGGER = 5,
	MUTE = 6,
	UNMUTE = 7,
	SET_VOICE_PITCH = 8,
	RESET_VOICE_PICTH = 9,
	SET_VOICE_VOLUME = 0xA,
	RESET_VOICE_VOLUME = 0xB,
	SET_BUS_VOLUME = 0xC,
	RESET_BUS_VOLUME = 0xD,
	SET_LOWPASS_FILTER = 0xE,
	RESET_LOWPASS_FILTER = 0xF,
	ENABLE_STATE = 0x10,
	DIABLE_STATE = 0x11,
	SET_STATE = 0x12,
	SET_GAME_PARAMETER = 0x13,
	RESET_GAME_PARAMETER = 0x14,
	SET_SWITCH = 0x19,
	TOGGLE_BYPASS = 0x1A,
	RESET_BYPASS = 0x1B,
	BREAK = 0x1C,
	SEEK = 0x1E,
}
enum HIRC_03_PARAMETER_TYPE {
	DELAY = 0xF,
	FADE_IN_TIME = 0x10,
	PROBABILITY = 0x11,
}
